
version: '3.8'

services:
  # Aplicación Pokedex PWA
  pokedex-pwa:
    build: .
    container_name: pokedex_pwa
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - devops-net
    depends_on:
      - sonarqube
      - jenkins

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube_devops
    ports:
      - "9000:9000"
    networks:
      - devops-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_devops
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - devops-net
    volumes:
      - jenkins_home:/var/jenkins_home
      # Mapeo del socket de Docker para que Jenkins pueda ejecutar comandos de Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeo de binarios de Docker (opcional, dependiendo de tu OS, mejor instalar docker dentro del container con un Dockerfile custom, pero esto suele funcionar para tareas rápidas)
      - /usr/bin/docker:/usr/bin/docker 
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  devops-net:

volumes:
  sonar_data:
  jenkins_home: